// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompetition = "competition"

// Competition mapped from table <competition>
type Competition struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code string `gorm:"column:code;not null" json:"code"`
	Year int32  `gorm:"column:year;not null" json:"year"`
	UsID int32  `gorm:"column:us_id;not null" json:"us_id"`
}

// TableName Competition's table name
func (*Competition) TableName() string {
	return TableNameCompetition
}
