// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

const TableNameBetsPlaced = "bets_placed"

// BetsPlaced mapped from table <bets_placed>
type BetsPlaced struct {
	ID      int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MatchID int32   `gorm:"column:match_id;not null" json:"match_id"`
	Odds    int32   `gorm:"column:odds;not null" json:"odds"`
	Amount  float64 `gorm:"column:amount;not null" json:"amount"`
}

// TableName BetsPlaced's table name
func (*BetsPlaced) TableName() string {
	return TableNameBetsPlaced
}
