// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

import (
	"time"
)

const TableNameMatch = "match"

// Match mapped from table <match>
type Match struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Date              time.Time `gorm:"column:date;not null" json:"date"`
	HomeTeam          int32     `gorm:"column:home_team;not null" json:"home_team"`
	AwayTeam          int32     `gorm:"column:away_team;not null" json:"away_team"`
	Competition       int32     `gorm:"column:competition;not null" json:"competition"`
	HomeGoals         int32     `gorm:"column:home_goals;not null" json:"home_goals"`
	AwayGoals         int32     `gorm:"column:away_goals;not null" json:"away_goals"`
	HomeExpectedGoals float64   `gorm:"column:home_expected_goals" json:"home_expected_goals"`
	AwayExpectedGoals float64   `gorm:"column:away_expected_goals" json:"away_expected_goals"`
	UsID              int32     `gorm:"column:us_id;not null" json:"us_id"`
}

// TableName Match's table name
func (*Match) TableName() string {
	return TableNameMatch
}
