// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

const TableNamePlayer = "player"

// Player mapped from table <player>
type Player struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Position string `gorm:"column:position;not null" json:"position"`
	UsID     int32  `gorm:"column:us_id;not null" json:"us_id"`
}

// TableName Player's table name
func (*Player) TableName() string {
	return TableNamePlayer
}
