// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_model

const TableNameTeam = "team"

// Team mapped from table <team>
type Team struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
	UsID int32  `gorm:"column:us_id;not null" json:"us_id"`
}

// TableName Team's table name
func (*Team) TableName() string {
	return TableNameTeam
}
