// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Appearance  *appearance
	Competition *competition
	Match       *match
	Odds1x2     *odds1x2
	Player      *player
	Team        *team
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Appearance = &Q.Appearance
	Competition = &Q.Competition
	Match = &Q.Match
	Odds1x2 = &Q.Odds1x2
	Player = &Q.Player
	Team = &Q.Team
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Appearance:  newAppearance(db, opts...),
		Competition: newCompetition(db, opts...),
		Match:       newMatch(db, opts...),
		Odds1x2:     newOdds1x2(db, opts...),
		Player:      newPlayer(db, opts...),
		Team:        newTeam(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Appearance  appearance
	Competition competition
	Match       match
	Odds1x2     odds1x2
	Player      player
	Team        team
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Appearance:  q.Appearance.clone(db),
		Competition: q.Competition.clone(db),
		Match:       q.Match.clone(db),
		Odds1x2:     q.Odds1x2.clone(db),
		Player:      q.Player.clone(db),
		Team:        q.Team.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Appearance:  q.Appearance.replaceDB(db),
		Competition: q.Competition.replaceDB(db),
		Match:       q.Match.replaceDB(db),
		Odds1x2:     q.Odds1x2.replaceDB(db),
		Player:      q.Player.replaceDB(db),
		Team:        q.Team.replaceDB(db),
	}
}

type queryCtx struct {
	Appearance  IAppearanceDo
	Competition ICompetitionDo
	Match       IMatchDo
	Odds1x2     IOdds1x2Do
	Player      IPlayerDo
	Team        ITeamDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Appearance:  q.Appearance.WithContext(ctx),
		Competition: q.Competition.WithContext(ctx),
		Match:       q.Match.WithContext(ctx),
		Odds1x2:     q.Odds1x2.WithContext(ctx),
		Player:      q.Player.WithContext(ctx),
		Team:        q.Team.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
