// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	model "sports-book.com/pkg/db_model"
)

func newAppearance(db *gorm.DB, opts ...gen.DOOption) appearance {
	_appearance := appearance{}

	_appearance.appearanceDo.UseDB(db, opts...)
	_appearance.appearanceDo.UseModel(&model.Appearance{})

	tableName := _appearance.appearanceDo.TableName()
	_appearance.ALL = field.NewAsterisk(tableName)
	_appearance.ID = field.NewInt32(tableName, "id")
	_appearance.Player = field.NewInt32(tableName, "player")
	_appearance.Match = field.NewInt32(tableName, "match")
	_appearance.Team = field.NewInt32(tableName, "team")
	_appearance.Goals = field.NewInt32(tableName, "goals")
	_appearance.ExpectedGoals = field.NewFloat64(tableName, "expected_goals")
	_appearance.ExpectedGoalsChain = field.NewFloat64(tableName, "expected_goals_chain")
	_appearance.ExpectedGoalsBuildup = field.NewFloat64(tableName, "expected_goals_buildup")
	_appearance.Assists = field.NewInt32(tableName, "assists")
	_appearance.ExpectedAssists = field.NewFloat64(tableName, "expected_assists")
	_appearance.KeyPasses = field.NewInt32(tableName, "key_passes")
	_appearance.YellowCards = field.NewInt32(tableName, "yellow_cards")
	_appearance.RedCards = field.NewInt32(tableName, "red_cards")
	_appearance.Minutes = field.NewInt32(tableName, "minutes")
	_appearance.UsID = field.NewInt32(tableName, "us_id")

	_appearance.fillFieldMap()

	return _appearance
}

type appearance struct {
	appearanceDo

	ALL                  field.Asterisk
	ID                   field.Int32
	Player               field.Int32
	Match                field.Int32
	Team                 field.Int32
	Goals                field.Int32
	ExpectedGoals        field.Float64
	ExpectedGoalsChain   field.Float64
	ExpectedGoalsBuildup field.Float64
	Assists              field.Int32
	ExpectedAssists      field.Float64
	KeyPasses            field.Int32
	YellowCards          field.Int32
	RedCards             field.Int32
	Minutes              field.Int32
	UsID                 field.Int32

	fieldMap map[string]field.Expr
}

func (a appearance) Table(newTableName string) *appearance {
	a.appearanceDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appearance) As(alias string) *appearance {
	a.appearanceDo.DO = *(a.appearanceDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appearance) updateTableName(table string) *appearance {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.Player = field.NewInt32(table, "player")
	a.Match = field.NewInt32(table, "match")
	a.Team = field.NewInt32(table, "team")
	a.Goals = field.NewInt32(table, "goals")
	a.ExpectedGoals = field.NewFloat64(table, "expected_goals")
	a.ExpectedGoalsChain = field.NewFloat64(table, "expected_goals_chain")
	a.ExpectedGoalsBuildup = field.NewFloat64(table, "expected_goals_buildup")
	a.Assists = field.NewInt32(table, "assists")
	a.ExpectedAssists = field.NewFloat64(table, "expected_assists")
	a.KeyPasses = field.NewInt32(table, "key_passes")
	a.YellowCards = field.NewInt32(table, "yellow_cards")
	a.RedCards = field.NewInt32(table, "red_cards")
	a.Minutes = field.NewInt32(table, "minutes")
	a.UsID = field.NewInt32(table, "us_id")

	a.fillFieldMap()

	return a
}

func (a *appearance) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appearance) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 15)
	a.fieldMap["id"] = a.ID
	a.fieldMap["player"] = a.Player
	a.fieldMap["match"] = a.Match
	a.fieldMap["team"] = a.Team
	a.fieldMap["goals"] = a.Goals
	a.fieldMap["expected_goals"] = a.ExpectedGoals
	a.fieldMap["expected_goals_chain"] = a.ExpectedGoalsChain
	a.fieldMap["expected_goals_buildup"] = a.ExpectedGoalsBuildup
	a.fieldMap["assists"] = a.Assists
	a.fieldMap["expected_assists"] = a.ExpectedAssists
	a.fieldMap["key_passes"] = a.KeyPasses
	a.fieldMap["yellow_cards"] = a.YellowCards
	a.fieldMap["red_cards"] = a.RedCards
	a.fieldMap["minutes"] = a.Minutes
	a.fieldMap["us_id"] = a.UsID
}

func (a appearance) clone(db *gorm.DB) appearance {
	a.appearanceDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a appearance) replaceDB(db *gorm.DB) appearance {
	a.appearanceDo.ReplaceDB(db)
	return a
}

type appearanceDo struct{ gen.DO }

type IAppearanceDo interface {
	gen.SubQuery
	Debug() IAppearanceDo
	WithContext(ctx context.Context) IAppearanceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppearanceDo
	WriteDB() IAppearanceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppearanceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppearanceDo
	Not(conds ...gen.Condition) IAppearanceDo
	Or(conds ...gen.Condition) IAppearanceDo
	Select(conds ...field.Expr) IAppearanceDo
	Where(conds ...gen.Condition) IAppearanceDo
	Order(conds ...field.Expr) IAppearanceDo
	Distinct(cols ...field.Expr) IAppearanceDo
	Omit(cols ...field.Expr) IAppearanceDo
	Join(table schema.Tabler, on ...field.Expr) IAppearanceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppearanceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppearanceDo
	Group(cols ...field.Expr) IAppearanceDo
	Having(conds ...gen.Condition) IAppearanceDo
	Limit(limit int) IAppearanceDo
	Offset(offset int) IAppearanceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppearanceDo
	Unscoped() IAppearanceDo
	Create(values ...*model.Appearance) error
	CreateInBatches(values []*model.Appearance, batchSize int) error
	Save(values ...*model.Appearance) error
	First() (*model.Appearance, error)
	Take() (*model.Appearance, error)
	Last() (*model.Appearance, error)
	Find() ([]*model.Appearance, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Appearance, err error)
	FindInBatches(result *[]*model.Appearance, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Appearance) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppearanceDo
	Assign(attrs ...field.AssignExpr) IAppearanceDo
	Joins(fields ...field.RelationField) IAppearanceDo
	Preload(fields ...field.RelationField) IAppearanceDo
	FirstOrInit() (*model.Appearance, error)
	FirstOrCreate() (*model.Appearance, error)
	FindByPage(offset int, limit int) (result []*model.Appearance, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppearanceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appearanceDo) Debug() IAppearanceDo {
	return a.withDO(a.DO.Debug())
}

func (a appearanceDo) WithContext(ctx context.Context) IAppearanceDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appearanceDo) ReadDB() IAppearanceDo {
	return a.Clauses(dbresolver.Read)
}

func (a appearanceDo) WriteDB() IAppearanceDo {
	return a.Clauses(dbresolver.Write)
}

func (a appearanceDo) Session(config *gorm.Session) IAppearanceDo {
	return a.withDO(a.DO.Session(config))
}

func (a appearanceDo) Clauses(conds ...clause.Expression) IAppearanceDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appearanceDo) Returning(value interface{}, columns ...string) IAppearanceDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appearanceDo) Not(conds ...gen.Condition) IAppearanceDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appearanceDo) Or(conds ...gen.Condition) IAppearanceDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appearanceDo) Select(conds ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appearanceDo) Where(conds ...gen.Condition) IAppearanceDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appearanceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IAppearanceDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a appearanceDo) Order(conds ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appearanceDo) Distinct(cols ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appearanceDo) Omit(cols ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appearanceDo) Join(table schema.Tabler, on ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appearanceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appearanceDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appearanceDo) Group(cols ...field.Expr) IAppearanceDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appearanceDo) Having(conds ...gen.Condition) IAppearanceDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appearanceDo) Limit(limit int) IAppearanceDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appearanceDo) Offset(offset int) IAppearanceDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appearanceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppearanceDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appearanceDo) Unscoped() IAppearanceDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appearanceDo) Create(values ...*model.Appearance) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appearanceDo) CreateInBatches(values []*model.Appearance, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appearanceDo) Save(values ...*model.Appearance) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appearanceDo) First() (*model.Appearance, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Appearance), nil
	}
}

func (a appearanceDo) Take() (*model.Appearance, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Appearance), nil
	}
}

func (a appearanceDo) Last() (*model.Appearance, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Appearance), nil
	}
}

func (a appearanceDo) Find() ([]*model.Appearance, error) {
	result, err := a.DO.Find()
	return result.([]*model.Appearance), err
}

func (a appearanceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Appearance, err error) {
	buf := make([]*model.Appearance, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appearanceDo) FindInBatches(result *[]*model.Appearance, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appearanceDo) Attrs(attrs ...field.AssignExpr) IAppearanceDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appearanceDo) Assign(attrs ...field.AssignExpr) IAppearanceDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appearanceDo) Joins(fields ...field.RelationField) IAppearanceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appearanceDo) Preload(fields ...field.RelationField) IAppearanceDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appearanceDo) FirstOrInit() (*model.Appearance, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Appearance), nil
	}
}

func (a appearanceDo) FirstOrCreate() (*model.Appearance, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Appearance), nil
	}
}

func (a appearanceDo) FindByPage(offset int, limit int) (result []*model.Appearance, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appearanceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appearanceDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appearanceDo) Delete(models ...*model.Appearance) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appearanceDo) withDO(do gen.Dao) *appearanceDo {
	a.DO = *do.(*gen.DO)
	return a
}
