// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db_query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	model "sports-book.com/pkg/db_model"
)

func newBetsPlaced(db *gorm.DB, opts ...gen.DOOption) betsPlaced {
	_betsPlaced := betsPlaced{}

	_betsPlaced.betsPlacedDo.UseDB(db, opts...)
	_betsPlaced.betsPlacedDo.UseModel(&model.BetsPlaced{})

	tableName := _betsPlaced.betsPlacedDo.TableName()
	_betsPlaced.ALL = field.NewAsterisk(tableName)
	_betsPlaced.ID = field.NewInt32(tableName, "id")
	_betsPlaced.MatchID = field.NewInt32(tableName, "match_id")
	_betsPlaced.Odds = field.NewInt32(tableName, "odds")
	_betsPlaced.Amount = field.NewFloat64(tableName, "amount")

	_betsPlaced.fillFieldMap()

	return _betsPlaced
}

type betsPlaced struct {
	betsPlacedDo

	ALL     field.Asterisk
	ID      field.Int32
	MatchID field.Int32
	Odds    field.Int32
	Amount  field.Float64

	fieldMap map[string]field.Expr
}

func (b betsPlaced) Table(newTableName string) *betsPlaced {
	b.betsPlacedDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b betsPlaced) As(alias string) *betsPlaced {
	b.betsPlacedDo.DO = *(b.betsPlacedDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *betsPlaced) updateTableName(table string) *betsPlaced {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt32(table, "id")
	b.MatchID = field.NewInt32(table, "match_id")
	b.Odds = field.NewInt32(table, "odds")
	b.Amount = field.NewFloat64(table, "amount")

	b.fillFieldMap()

	return b
}

func (b *betsPlaced) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *betsPlaced) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 4)
	b.fieldMap["id"] = b.ID
	b.fieldMap["match_id"] = b.MatchID
	b.fieldMap["odds"] = b.Odds
	b.fieldMap["amount"] = b.Amount
}

func (b betsPlaced) clone(db *gorm.DB) betsPlaced {
	b.betsPlacedDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b betsPlaced) replaceDB(db *gorm.DB) betsPlaced {
	b.betsPlacedDo.ReplaceDB(db)
	return b
}

type betsPlacedDo struct{ gen.DO }

type IBetsPlacedDo interface {
	gen.SubQuery
	Debug() IBetsPlacedDo
	WithContext(ctx context.Context) IBetsPlacedDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBetsPlacedDo
	WriteDB() IBetsPlacedDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBetsPlacedDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBetsPlacedDo
	Not(conds ...gen.Condition) IBetsPlacedDo
	Or(conds ...gen.Condition) IBetsPlacedDo
	Select(conds ...field.Expr) IBetsPlacedDo
	Where(conds ...gen.Condition) IBetsPlacedDo
	Order(conds ...field.Expr) IBetsPlacedDo
	Distinct(cols ...field.Expr) IBetsPlacedDo
	Omit(cols ...field.Expr) IBetsPlacedDo
	Join(table schema.Tabler, on ...field.Expr) IBetsPlacedDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBetsPlacedDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBetsPlacedDo
	Group(cols ...field.Expr) IBetsPlacedDo
	Having(conds ...gen.Condition) IBetsPlacedDo
	Limit(limit int) IBetsPlacedDo
	Offset(offset int) IBetsPlacedDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBetsPlacedDo
	Unscoped() IBetsPlacedDo
	Create(values ...*model.BetsPlaced) error
	CreateInBatches(values []*model.BetsPlaced, batchSize int) error
	Save(values ...*model.BetsPlaced) error
	First() (*model.BetsPlaced, error)
	Take() (*model.BetsPlaced, error)
	Last() (*model.BetsPlaced, error)
	Find() ([]*model.BetsPlaced, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BetsPlaced, err error)
	FindInBatches(result *[]*model.BetsPlaced, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BetsPlaced) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBetsPlacedDo
	Assign(attrs ...field.AssignExpr) IBetsPlacedDo
	Joins(fields ...field.RelationField) IBetsPlacedDo
	Preload(fields ...field.RelationField) IBetsPlacedDo
	FirstOrInit() (*model.BetsPlaced, error)
	FirstOrCreate() (*model.BetsPlaced, error)
	FindByPage(offset int, limit int) (result []*model.BetsPlaced, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBetsPlacedDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b betsPlacedDo) Debug() IBetsPlacedDo {
	return b.withDO(b.DO.Debug())
}

func (b betsPlacedDo) WithContext(ctx context.Context) IBetsPlacedDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b betsPlacedDo) ReadDB() IBetsPlacedDo {
	return b.Clauses(dbresolver.Read)
}

func (b betsPlacedDo) WriteDB() IBetsPlacedDo {
	return b.Clauses(dbresolver.Write)
}

func (b betsPlacedDo) Session(config *gorm.Session) IBetsPlacedDo {
	return b.withDO(b.DO.Session(config))
}

func (b betsPlacedDo) Clauses(conds ...clause.Expression) IBetsPlacedDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b betsPlacedDo) Returning(value interface{}, columns ...string) IBetsPlacedDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b betsPlacedDo) Not(conds ...gen.Condition) IBetsPlacedDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b betsPlacedDo) Or(conds ...gen.Condition) IBetsPlacedDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b betsPlacedDo) Select(conds ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b betsPlacedDo) Where(conds ...gen.Condition) IBetsPlacedDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b betsPlacedDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IBetsPlacedDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b betsPlacedDo) Order(conds ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b betsPlacedDo) Distinct(cols ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b betsPlacedDo) Omit(cols ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b betsPlacedDo) Join(table schema.Tabler, on ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b betsPlacedDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b betsPlacedDo) RightJoin(table schema.Tabler, on ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b betsPlacedDo) Group(cols ...field.Expr) IBetsPlacedDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b betsPlacedDo) Having(conds ...gen.Condition) IBetsPlacedDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b betsPlacedDo) Limit(limit int) IBetsPlacedDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b betsPlacedDo) Offset(offset int) IBetsPlacedDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b betsPlacedDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBetsPlacedDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b betsPlacedDo) Unscoped() IBetsPlacedDo {
	return b.withDO(b.DO.Unscoped())
}

func (b betsPlacedDo) Create(values ...*model.BetsPlaced) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b betsPlacedDo) CreateInBatches(values []*model.BetsPlaced, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b betsPlacedDo) Save(values ...*model.BetsPlaced) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b betsPlacedDo) First() (*model.BetsPlaced, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BetsPlaced), nil
	}
}

func (b betsPlacedDo) Take() (*model.BetsPlaced, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BetsPlaced), nil
	}
}

func (b betsPlacedDo) Last() (*model.BetsPlaced, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BetsPlaced), nil
	}
}

func (b betsPlacedDo) Find() ([]*model.BetsPlaced, error) {
	result, err := b.DO.Find()
	return result.([]*model.BetsPlaced), err
}

func (b betsPlacedDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BetsPlaced, err error) {
	buf := make([]*model.BetsPlaced, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b betsPlacedDo) FindInBatches(result *[]*model.BetsPlaced, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b betsPlacedDo) Attrs(attrs ...field.AssignExpr) IBetsPlacedDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b betsPlacedDo) Assign(attrs ...field.AssignExpr) IBetsPlacedDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b betsPlacedDo) Joins(fields ...field.RelationField) IBetsPlacedDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b betsPlacedDo) Preload(fields ...field.RelationField) IBetsPlacedDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b betsPlacedDo) FirstOrInit() (*model.BetsPlaced, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BetsPlaced), nil
	}
}

func (b betsPlacedDo) FirstOrCreate() (*model.BetsPlaced, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BetsPlaced), nil
	}
}

func (b betsPlacedDo) FindByPage(offset int, limit int) (result []*model.BetsPlaced, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b betsPlacedDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b betsPlacedDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b betsPlacedDo) Delete(models ...*model.BetsPlaced) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *betsPlacedDo) withDO(do gen.Dao) *betsPlacedDo {
	b.DO = *do.(*gen.DO)
	return b
}
