// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAppearance = "appearance"

// Appearance mapped from table <appearance>
type Appearance struct {
	ID                   int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Player               int32   `gorm:"column:player;not null" json:"player"`
	Match                int32   `gorm:"column:match;not null" json:"match"`
	Team                 int32   `gorm:"column:team;not null" json:"team"`
	Goals                int32   `gorm:"column:goals;not null" json:"goals"`
	ExpectedGoals        float64 `gorm:"column:expected_goals" json:"expected_goals"`
	ExpectedGoalsChain   float64 `gorm:"column:expected_goals_chain" json:"expected_goals_chain"`
	ExpectedGoalsBuildup float64 `gorm:"column:expected_goals_buildup" json:"expected_goals_buildup"`
	Assists              int32   `gorm:"column:assists;not null" json:"assists"`
	ExpectedAssists      float64 `gorm:"column:expected_assists" json:"expected_assists"`
	KeyPasses            int32   `gorm:"column:key_passes;not null" json:"key_passes"`
	YellowCards          int32   `gorm:"column:yellow_cards;not null" json:"yellow_cards"`
	RedCards             int32   `gorm:"column:red_cards;not null" json:"red_cards"`
	Minutes              int32   `gorm:"column:minutes;not null" json:"minutes"`
	UsID                 int32   `gorm:"column:us_id;not null" json:"us_id"`
}

// TableName Appearance's table name
func (*Appearance) TableName() string {
	return TableNameAppearance
}
